### ISSUE TITLE
Online Booking System for British Columbia Supreme Court

### ISSUE THREAD

**Issue by bcdevex** [bcgov/scj-online-booking-system#1]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-online-booking-system-for-british-columbia-supreme-court">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-online-booking-system-for-british-columbia-supreme-court">visit the opportunity page</a>. The opportunity closes on <b>Friday, September 28, 2018</b>.</p>

**Comment by SteveChapmanBCDX** [comment]
Hello everyone - we are excited to post this new opportunity. If you have any questions, please let me know.

**Comment by kheera** [comment]
Hi Steve, This is a very interesting opportunity. Are bids expected by a single contractor only or is a team option okay? If a team is okay, can some team members be based in the USA?

**Comment by lucasyvas** [comment]
Is there a rough estimate how much on-site time will be required? If team members are allowed, we are both in Victoria.

Also, I'm curious if there is a desired timeline for 100% completion.

Thanks!

**Comment by SteveChapmanBCDX** [comment]
Hi @lucasyvas -

You will meet with the development team in Vancouver in-person once per month.  Other meetings can be attended either virtually or in-person.

The expected deadline for this project is March 31, 2019.

**Comment by SteveChapmanBCDX** [comment]
Hi @kheera -

Please see my response immediately above regarding on-site work in Vancouver.  All team members (regardless of their location) will have to meet that requirement.

As far as who may submit a bid, either a single contractor or a company may do so.  USA-based team members are fine so long as they can meet all requirements (e.g., on-site meetings in Vancouver).

**Comment by scchapma** [comment]
**Addendum**

This opportunity's "Program" and "Project" have changed.  The "Program" has been changed from "BCDevExchange" to "British Columbia Superior Courts".  the "Project" has been changed from "BCDevExchange Application" to "Online Booking System for British Columbia Supreme Court".

**Comment by velogordo** [comment]
Hi @SteveChapmanBCDX - some questions about the SRS:

3.1.2 - REQ-1
Can we assume that all users will have credentials and there is no need for a "register" step in the app or a "forgot your credentials" feature? 

3.1.2 - REQ-3
The requirement references 3 bookings in 1 day. Does this mean the number of total bookings a single user can perform within a 24 hour period of time, or does this mean the total number of conferences booked on a particular date in the future. 

E.g. On Monday Sept 24, 2018, Gord books 3 conferences for various dates in the future. He can't book any more conferences until Tuesday Sept 25. 

OR

Gord books 3 bookings for Jan 5, 2019 and has used up his "3 for a day" limit. He can, during the same session sitting with the application, book another 3 for Jan 6 2019, and so-on (unlimited number of conferences booked in one user session, but no more than 3 for the target date)?

3.2.2 - REQ-1
Will the SCSS API be responsible for scoping the search such that the user just needs a location and a file number in order to retrieve the appropriate matter? Or is envisioned there would need to be a search results page such that duplicate file numbers and matches in style of cause are clarified (much like CSO search). 

E.g. VLC-123456 actually corresponds to 4 files (Probate, Family Law, Motor Vehicle, & Civil General). Will SCSS limit the search to open matters / only Family Law such that 123456 will mean an exact match? 

3.4.2 - REQ-2
An Appendix 1 is mentioned in the SRS, but not provided. Can we receive a copy?

3.5.2 - REQ-3
Can you confirm the existence of the API that allows a booking to SCSS to be added? 

General question: cancellations

If users need to cancel their booking after the fact, can we assume that will be done via scheduling staff over the phone (and not going back into a previously made online booking and cancelling/modifying)?

**Comment by CGIVictoria** [comment]
For the Code Challenge, what is the expected duration?   (ie. is it similar to Sprint with Us initiatives)

**Comment by SteveChapmanBCDX** [comment]
Hi @CGIVictoria -

The Code Challenge for this opportunity will be less complicated than the Code Challenges for the last two Sprint With Us opportunities.  We anticipate that the Code Challenge for this opportunity will take approximately 2 days to complete.

**Comment by SteveChapmanBCDX** [comment]
Hi @velogordo -

Please find my responses to your questions inline below:

> Hi @SteveChapmanBCDX - some questions about the SRS:
> 
> 3.1.2 - REQ-1
> Can we assume that all users will have credentials and there is no need for a "register" step in the app or a "forgot your credentials" feature?
> 
Yes, the users will all have credentials (BCeID and BCID which has a separate setup and forgot your password section on its own).

> 3.1.2 - REQ-3
> The requirement references 3 bookings in 1 day. Does this mean the number of total bookings a single user can perform within a 24 hour period of time, or does this mean the total number of conferences booked on a particular date in the future.
> 
> E.g. On Monday Sept 24, 2018, Gord books 3 conferences for various dates in the future. He can't book any more conferences until Tuesday Sept 25.
> 
> OR
> 
> Gord books 3 bookings for Jan 5, 2019 and has used up his "3 for a day" limit. He can, during the same session sitting with the application, book another 3 for Jan 6 2019, and so-on (unlimited number of conferences booked in one user session, but no more than 3 for the target date)?
> 
Your scenario #1 is the correct use case.  Users can only book 3 conferences per 24 hour period.  This is a contingency plan against bots booking hundreds of conferences soaking up all available dates.  Typical users rarely book more than once conference a week.
> 3.2.2 - REQ-1
> Will the SCSS API be responsible for scoping the search such that the user just needs a location and a file number in order to retrieve the appropriate matter? Or is envisioned there would need to be a search results page such that duplicate file numbers and matches in style of cause are clarified (much like CSO search).
> 
> E.g. VLC-123456 actually corresponds to 4 files (Probate, Family Law, Motor Vehicle, & Civil General). Will SCSS limit the search to open matters / only Family Law such that 123456 will mean an exact match?
> 
Yes, location and action number will be required to select the exact case.  Note that the SCSS API will limit the available action numbers to open actions that would require a conference. 
> 3.4.2 - REQ-2
> An Appendix 1 is mentioned in the SRS, but not provided. Can we receive a copy?
> 
Please disregard the remark in the SRS that refers to the calendar format set out in Appendix 1.  The required format is not predetermined and will be open to negotiation.
> 3.5.2 - REQ-3
> Can you confirm the existence of the API that allows a booking to SCSS to be added?
> 
Yes, an API exists that allows the SCSS to be updated.
> General question: cancellations
> 

> If users need to cancel their booking after the fact, can we assume that will be done via scheduling staff over the phone (and not going back into a previously made online booking and 
> cancelling/modifying)?

Yes, cancellations will be done over the phone for this first phase of the project.

**Comment by spallister** [comment]
Afternoon @SteveChapmanBCDX - hoping you might be able to answer the following questions:
1. Is it expected that Online Booking System (OBS) application users will directly call the SCSS API (e.g. OBS User Agent <-> SCSS API), or are all SCSS API requests to flow through an OBS API that will handle authorization (e.g. OBS User Agent <-> OBS API <-> SCSS API).
    - If OBS users will directly call the SCSS API, can you please share how it will be secured (e.g. OAuth Bearer Tokens, or other).
    - Otherwise, if OBS users will call an OBS API (which will in turn call the SCSS API, as necessary), is there any preference for how it is secured.
2. For tracking the number of bookings scheduled (i.e. to enforce the three bookings/day limit), can we assume that the SCSS API will be extended with an appropriate endpoint from which the number of bookings (or even a list of booking summaries) made during a specified time period is retrieved.  Otherwise, is it expected that the OBS shall persist user's booking counter state outside of the SCSS API (e.g. within an OBS Database).
3. Is there currently any sense of the desired look and feel for the OBS to be implemented?  In particular, is it anticipated that the OWS will be hosted at a standalone URL (e.g. https://scheduling.courts.gov.bc.ca), and share the look and feel of other recently launched government web applications (e.g. https://billing-and-payment.revenueservicesbc.gov.bc.ca)

Thanks for your help!

**Comment by SteveChapmanBCDX** [comment]
> Afternoon @SteveChapmanBCDX - hoping you might be able to answer the following questions:
> 
> 1. Is it expected that Online Booking System (OBS) application users will directly call the SCSS API (e.g. OBS User Agent <-> SCSS API), or are all SCSS API requests to flow through an OBS API that will handle authorization (e.g. OBS User Agent <-> OBS API <-> SCSS API).
>    
>    * If OBS users will directly call the SCSS API, can you please share how it will be secured (e.g. OAuth Bearer Tokens, or other).
>    * Otherwise, if OBS users will call an OBS API (which will in turn call the SCSS API, as necessary), is there any preference for how it is secured.
OBS users will call an OBS API.  There is no preference on how it is secured.
> 2. For tracking the number of bookings scheduled (i.e. to enforce the three bookings/day limit), can we assume that the SCSS API will be extended with an appropriate endpoint from which the number of bookings (or even a list of booking summaries) made during a specified time period is retrieved.  Otherwise, is it expected that the OBS shall persist user's booking counter state outside of the SCSS API (e.g. within an OBS Database).
> 3. Is there currently any sense of the desired look and feel for the OBS to be implemented?  In particular, is it anticipated that the OWS will be hosted at a standalone URL (e.g. https://scheduling.courts.gov.bc.ca), and share the look and feel of other recently launched government web applications (e.g. https://billing-and-payment.revenueservicesbc.gov.bc.ca)
> 
> Thanks for your help!

**Comment by CGIVictoria** [comment]
Unsubscribe



On September 28, 2018 at 11:00:25 AM, Steve Chapman (notifications@github.com<mailto:notifications@github.com>) wrote:

Afternoon @SteveChapmanBCDX<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SteveChapmanBCDX&d=DwMFaQ&c=H50I6Bh8SW87d_bXfZP_8g&r=MyEQkhuWo3UnYpx54Jeqdg&m=bFOOkPwk6T8s6oB_HUrxDzf2fe1lHoqYkvNDSAXljLA&s=y4RbdPafuDJ_CrcZe8ZUL7cgE6IO8LjCquwwFhRkOFY&e=> - hoping you might be able to answer the following questions:

  1.  Is it expected that Online Booking System (OBS) application users will directly call the SCSS API (e.g. OBS User Agent <-> SCSS API), or are all SCSS API requests to flow through an OBS API that will handle authorization (e.g. OBS User Agent <-> OBS API <-> SCSS API).

     *   If OBS users will directly call the SCSS API, can you please share how it will be secured (e.g. OAuth Bearer Tokens, or other).
     *   Otherwise, if OBS users will call an OBS API (which will in turn call the SCSS API, as necessary), is there any preference for how it is secured.
OBS users will call an OBS API. There is no preference on how it is secured.
  2.  For tracking the number of bookings scheduled (i.e. to enforce the three bookings/day limit), can we assume that the SCSS API will be extended with an appropriate endpoint from which the number of bookings (or even a list of booking summaries) made during a specified time period is retrieved. Otherwise, is it expected that the OBS shall persist user's booking counter state outside of the SCSS API (e.g. within an OBS Database).

  3.  Is there currently any sense of the desired look and feel for the OBS to be implemented? In particular, is it anticipated that the OWS will be hosted at a standalone URL (e.g. https://scheduling.courts.gov.bc.ca<https://urldefense.proofpoint.com/v2/url?u=https-3A__scheduling.courts.gov.bc.ca&d=DwMFaQ&c=H50I6Bh8SW87d_bXfZP_8g&r=MyEQkhuWo3UnYpx54Jeqdg&m=bFOOkPwk6T8s6oB_HUrxDzf2fe1lHoqYkvNDSAXljLA&s=Z81HToDZSlZVvaIpy40PT0DtWlDGUvBLwiMc9LphlfM&e=>), and share the look and feel of other recently launched government web applications (e.g. https://billing-and-payment.revenueservicesbc.gov.bc.ca<https://urldefense.proofpoint.com/v2/url?u=https-3A__billing-2Dand-2Dpayment.revenueservicesbc.gov.bc.ca&d=DwMFaQ&c=H50I6Bh8SW87d_bXfZP_8g&r=MyEQkhuWo3UnYpx54Jeqdg&m=bFOOkPwk6T8s6oB_HUrxDzf2fe1lHoqYkvNDSAXljLA&s=RRVvQPYz2hUF5jJezSdrgyogMB_5-LVQBrw7oE4kLwk&e=>)

Thanks for your help!

**Comment by SteveChapmanBCDX** [comment]
Hi @spallister -

Please see my responses to your questions inline below:

> Afternoon @SteveChapmanBCDX - hoping you might be able to answer the following questions:
> 
> 1. Is it expected that Online Booking System (OBS) application users will directly call the SCSS API (e.g. OBS User Agent <-> SCSS API), or are all SCSS API requests to flow through an OBS API that will handle authorization (e.g. OBS User Agent <-> OBS API <-> SCSS API).
>    
>    * If OBS users will directly call the SCSS API, can you please share how it will be secured (e.g. OAuth Bearer Tokens, or other).
>    * Otherwise, if OBS users will call an OBS API (which will in turn call the SCSS API, as necessary), is there any preference for how it is secured.

OBS users will call an OBS API.  There is now preference for how that is secured.

> 2. For tracking the number of bookings scheduled (i.e. to enforce the three bookings/day limit), can we assume that the SCSS API will be extended with an appropriate endpoint from which the number of bookings (or even a list of booking summaries) made during a specified time period is retrieved.  Otherwise, is it expected that the OBS shall persist user's booking counter state outside of the SCSS API (e.g. within an OBS Database).

Assume that there will be an OBS database to monitor these counters.

> 3. Is there currently any sense of the desired look and feel for the OBS to be implemented?  In particular, is it anticipated that the OWS will be hosted at a standalone URL (e.g. https://scheduling.courts.gov.bc.ca), and share the look and feel of other recently launched government web applications (e.g. https://billing-and-payment.revenueservicesbc.gov.bc.ca)
> 
> Thanks for your help!

The OBS will be hosted at a stand alone URL.  The look and feel is negotiable.  The existing look, feel and style of existing government web applications is a good pattern.

**Comment by praveen-aot** [comment]
Hi @SteveChapmanBCDX 

The instructions state that our proposal can be uploaded under the attachments tab, however, we cannot see such a tab. The only tabs available are Developer, Company, Proposal, and Terms.

Thanks for your help!

**Comment by mark-a-wilson** [comment]
@pcrnair -- sorry it's a bad UX thing in our app – you need to have your proposal saved in 'Draft" before you can attach documents to it.

If you click the "Save & Close" button, then go back into your proposal, you should then see the Attachments tab.

**Comment by praveen-aot** [comment]
Thanks Mark....

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by SteveChapmanBCDX** [comment]
This opportunity has been assigned to @velogordo.

If anybody who submitted a proposal would like a debrief (and has not already received one), please contact me at through the Developers' Exchange email address at bcdevexchange@gov.bc.ca.

**Comment by jleach** [comment]
Stale issue. Closing as this repo is no longer under active development.
